spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: MEDICO-AUTH
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        jdbc:
          batch-size: 30
          order_inserts: true
  datasource-booking:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://192.168.68.69:5432/odmdb?currentSchema=medico_customer
    driverClassName: org.postgresql.Driver
    username: odmusr
    password: odmpwd
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 3
  datasource-admin:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://192.168.68.69:5432/odmdb?currentSchema=medico_auth
    driverClassName: org.postgresql.Driver
    username: odmusr
    password: odmpwd
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 3
  redis:
    host: 192.168.68.200
    port: 9279
    ssl: false
    timeout: 12m
    database: 0
    sentinel:
      master: mymaster
      nodes: 192.168.68.200:26379
    password: redis#2016
  mail:
    host: codee.vn
    port: 465
    username: no_reply@codee.vn
    password: 1Yjsj!28
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          ssl:
            enable: true


eureka:
  client:
    serviceUrl:
      defaultZone: '${EUREKA_URI:http://192.168.68.69:9761/eureka/}'
logging:
  level:
    org.hibernate.*: ERROR
keycloak:
  ssl-required: none
  realm: UNI_MEDICO
  resource: webapp
  # keycloak configuration
  bearer-only: true
  auth-server-url: http://192.168.68.69:8998/auth
  credentials:
    secret: fwUsLh4Ca49Zsq5Qdwi7HgN7ZhlF1GZD
oauth:
  client-id: webapp
  client-secret: fwUsLh4Ca49Zsq5Qdwi7HgN7ZhlF1GZD
  scope: openid microprofile-jwt
  token-url: http://192.168.68.69:8998/auth/realms/UNI_MEDICO/protocol/openid-connect/token
  user-info-url: http://192.168.68.69:8998/auth/realms/UNI_MEDICO/protocol/openid-connect/userinfo
  user-logout-url: http://192.168.68.69:8998/auth/realms/UNI_MEDICO/protocol/openid-connect/logout
whitelist:
  patterns: /**
  ip-address: 192.168.68.0/24
server:
  port: 8081

topic:
  login:
    expired: 5


